// @ts-ignore Generated by the OpenNext build.
import handler from "./.open-next/worker.js";
import {
  berlinParts,
  isValidState,
  reconcileScheduleState,
  type ScheduleState,
  type WeeklySchedule,
} from "./lib/scheduleData";

type Env = {
  SITE_DATA: {
    get(key: string, type: "json"): Promise<unknown>;
    put(key: string, value: string): Promise<void>;
  };
  DISCORD_STREAMPLAN_WEBHOOK_URL?: string;
};
function discordContent(week: WeeklySchedule) {
  const lines = week.days.map((day) => {
    const date = day.date.split("-").reverse().slice(0, 2).join(".");
    if (!day.streams.length) return `**${day.label}, ${date}.** — Offline`;
    return `**${day.label}, ${date}.** — ${day.streams.map((stream) => stream.segments.map((segment) => `${segment.start} ${segment.title}`).join(" → ")).join("\n↳ ")}`;
  });
  return `📅 **Streamplan · Woche ab ${week.weekStart.split("-").reverse().join(".")}**\n\n${lines.join("\n")}\n\n_Zeiten können sich kurzfristig ändern._`;
}
async function replaceDiscord(state: ScheduleState, env: Env) {
  const webhook = env.DISCORD_STREAMPLAN_WEBHOOK_URL;
  if (!webhook) return;
  if (state.discordMessageId) {
    const deletion = await fetch(
      `${webhook}/messages/${encodeURIComponent(state.discordMessageId)}`,
      { method: "DELETE" },
    );
    if (!deletion.ok && deletion.status !== 404)
      throw new Error(`Discord delete failed: ${deletion.status}`);
  }
  const response = await fetch(`${webhook}?wait=true`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      content: discordContent(state.current),
      allowed_mentions: { parse: [] },
    }),
  });
  if (!response.ok) throw new Error(`Discord post failed: ${response.status}`);
  const message = (await response.json()) as { id?: string };
  if (!message.id) throw new Error("Discord response has no message id");
  state.discordMessageId = message.id;
}

export default {
  fetch: handler.fetch,
  async scheduled(event: { scheduledTime: number }, env: Env) {
    const local = berlinParts(new Date(event.scheduledTime));
    if (local.weekday !== "Mon" || local.hour !== "00" || local.minute !== "01")
      return;
    const saved = await env.SITE_DATA.get("stream-schedule-v2", "json");
    if (!isValidState(saved)) return;
    const result = reconcileScheduleState(saved, new Date(event.scheduledTime));
    if (!result.changed) return;
    await replaceDiscord(result.state, env);
    await env.SITE_DATA.put("stream-schedule-v2", JSON.stringify(result.state));
  },
};

// @ts-ignore Generated by the OpenNext build; required by optional OpenNext caches.
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";

